CREATE TABLE Album(
  AlbumID INT PRIMARY KEY AUTO_INCREMENT,
  Nome VARCHAR(50),
  Preco DECIMAL(5, 2),
  ArtistaID INT,
  FOREIGN KEY (ArtistaID) REFERENCES Artista(ArtistaID)  
);

CREATE TABLE Artista(
  ArtistaID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Nome VARCHAR(50)
)

CREATE TABLE Musica(
  MusicaID INT PRIMARY KEY AUTO_INCREMENT,
  Nome VARCHAR(100),
  AlbumID INT,
  FOREIGN KEY (AlbumID) REFERENCES Album(AlbumID)
)

